{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.daemonset_metadata_agent }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.metadata }}
{{- $mounts_neutron_metadata_agent := .Values.pod.mounts.neutron_metadata_agent.neutron_metadata_agent }}
{{- $mounts_neutron_metadata_agent_init := .Values.pod.mounts.neutron_metadata_agent.init_container }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-metadata-agent
spec:
{{ tuple $envAll "metadata_agent" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "neutron" "metadata-agent" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      nodeSelector:
        {{ .Values.labels.agent.metadata.node_selector_key }}: {{ .Values.labels.agent.metadata.node_selector_value }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
{{ tuple $envAll $dependencies $mounts_neutron_metadata_agent_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: neutron-metadata-agent-init
          image: {{ .Values.images.tags.neutron_metadata }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.agent.metadata | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          securityContext:
            runAsUser: {{ .Values.pod.user.neutron.uid }}
          command:
            - /tmp/neutron-metadata-agent-init.sh
          volumeMounts:
            - name: neutron-bin
              mountPath: /tmp/neutron-metadata-agent-init.sh
              subPath: neutron-metadata-agent-init.sh
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared
      containers:
        - name: neutron-metadata-agent
          image: {{ .Values.images.tags.neutron_metadata }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.agent.metadata | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          securityContext:
            runAsUser: {{ .Values.pod.user.neutron.uid }}
            privileged: true
          ports:
            - containerPort: {{ .Values.network.metadata.port }}
          command:
            - /tmp/neutron-metadata-agent.sh
          volumeMounts:
            - name: neutron-bin
              mountPath: /tmp/neutron-metadata-agent.sh
              subPath: neutron-metadata-agent.sh
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/plugins/ml2/ml2_conf.ini
              subPath: ml2_conf.ini
              readOnly: true
            {{- if eq .Values.network.backend "ovs" }}
            - name: neutron-etc
              mountPath: /etc/neutron/plugins/ml2/openvswitch_agent.ini
              subPath: openvswitch_agent.ini
              readOnly: true
            - name: runopenvswitch
              mountPath: /run/openvswitch
            {{- end }}
            - name: neutron-etc
              mountPath: /etc/neutron/metadata_agent.ini
              subPath: metadata_agent.ini
              readOnly: true
            - name: neutron-etc
              # NOTE (Portdirect): We mount here to override Kollas
              # custom sudoers file when using Kolla images, this
              # location will also work fine for other images.
              mountPath: /etc/sudoers.d/kolla_neutron_sudoers
              subPath: neutron_sudoers
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.conf
              subPath: rootwrap.conf
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/debug.filters
              subPath: debug.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/dibbler.filters
              subPath: dibbler.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/ipset-firewall.filters
              subPath: ipset-firewall.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/l3.filters
              subPath: l3.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/netns-cleanup.filters
              subPath: netns-cleanup.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/dhcp.filters
              subPath: dhcp.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/ebtables.filters
              subPath: ebtables.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/iptables-firewall.filters
              subPath: iptables-firewall.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/linuxbridge-plugin.filters
              subPath: linuxbridge-plugin.filters
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/rootwrap.d/openvswitch-plugin.filters
              subPath: openvswitch-plugin.filters
              readOnly: true
            - name: socket
              mountPath: /var/lib/neutron/stackanetes
            - name: pod-shared
              mountPath: /tmp/pod-shared
              readOnly: true
{{ if $mounts_neutron_metadata_agent.volumeMounts }}{{ toYaml $mounts_neutron_metadata_agent.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: neutron-bin
          configMap:
            name: neutron-bin
            defaultMode: 0555
        - name: neutron-etc
          configMap:
            name: neutron-etc
            defaultMode: 0444
        {{- if eq .Values.network.backend "ovs" }}
        - name: runopenvswitch
          hostPath:
            path: /run/openvswitch
        {{- end }}
        - name: socket
          hostPath:
            path: /var/lib/neutron/openstack-helm
        - name: pod-shared
          emptyDir: {}
{{ if $mounts_neutron_metadata_agent.volumes }}{{ toYaml $mounts_neutron_metadata_agent.volumes | indent 8 }}{{ end }}
{{- end }}
